package math4u2.parser.formula.parserNodes;

import math4u2.view.formula.*;
import math4u2.parser.formula.*;

/* Generated By:JJTree: Do not edit this line. ASTBraces.java */

/**
 * Klasse für geschweifte Klammern. Dient nur als Knoten für Zeilen von Matrizen
 * und Vektoren.
 * 
 * @author Christoph Beckmann
 *  
 */

public class ASTBraces extends SimpleNode {
    public ASTBraces(int id) {
        super(id);
    }

    public ASTBraces(fsParser p, int id) {
        super(p, id);
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
        ContainerBox cb;
        for (int i = 0; i < children.length; i++) {
            cb = new ContainerBox(ab.getRenderContext());
            jjtGetChild(i).bakeComponents(cb);
            ab.add(cb);
        }
    }

    /* (non-Javadoc)
     * @see math4u2.parser.formula.parserNodes.SimpleNode#toString()
     */
    public String toString() {
        StringBuffer sb= new StringBuffer();
        for (int i = 0; i < children.length; i++) {
            sb.append(jjtGetChild(i).toString());
            sb.append(",");
        }
        sb.deleteCharAt(sb.length()-1);
        return sb.toString();
    }

}