/* Generated By:JJTree: Do not edit this line. ASTIndeces.java */

package math4u2.parser.formula.parserNodes;

import math4u2.view.formula.*;
import math4u2.parser.formula.*;

/**
 * Klasse dient als Vaterknoten von ein oder mehrer Indeces.
 * 
 * @author Christoph Beckmann
 *  
 */

public class ASTIndeces extends SimpleNode {
    public ASTIndeces(int id) {
        super(id);
    }

    public ASTIndeces(fsParser p, int id) {
        super(p, id);
    }
    
    public void setName(String symbol) {
        super.symbol = symbol;
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
        for (int i = 0; i < children.length; i++) {
            jjtGetChild(i).bakeComponents(ab);
            if (i != children.length - 1)
                ab.add(new OrdBox(ab.getRenderContext(), ","));
        }
    }

    /* (non-Javadoc)
     * @see math4u2.parser.formula.parserNodes.SimpleNode#toString()
     */
    public String toString() {
        StringBuffer sb= new StringBuffer();
        if(symbol.equals("[")){
            sb.append("[");
            sb.append(jjtGetChild(0).toString());
            sb.append("]");
        }else{
            sb.append(symbol);
            sb.append(jjtGetChild(0).toString());
        }
        
        return sb.toString();
    }

}