package math4u2.parser.formula.parserNodes;

import math4u2.view.formula.*;
import math4u2.parser.formula.*;

/* Generated By:JJTree: Do not edit this line. ASTNormalFunction.java */

/**
 * Klasse für Funktionen, die vom Benutzer benannt werden. Z.B.: f(x),
 * meineFunktion(x)
 * 
 * @author Christoph Beckmann
 */

public class ASTNormalFunction extends SimpleNode {

    public ASTNormalFunction(int id) {
        super(id);
    }

    public ASTNormalFunction(fsParser p, int id) {
        super(p, id);
    }


    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.formula.AtomicBox)
     */
    public void bakeComponents(AtomicBox ab) {
//        jjtGetChild(0).bakeComponents(ab);
//        BracketedBox bb = new BracketedBox(ab.getRenderContext());
//        jjtGetChild(1).bakeComponents(bb);
//        ab.add(bb);
        for(int i =0; i<jjtGetNumChildren();i++){
            jjtGetChild(i).bakeComponents(ab);
        }
    }

    /* (non-Javadoc)
     * @see math4u2.parser.formula.parserNodes.SimpleNode#toString()
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        for(int i =0; i<jjtGetNumChildren();i++){
            sb.append(jjtGetChild(i).toString());
        }
        return sb.toString();
    }

}