package math4u2.parser.formula.parserNodes;

import math4u2.view.formula.AtomicBox;
import math4u2.parser.formula.*;

/* Generated By:JJTree: Do not edit this line. ASTPraefixExpression.java */

/**
 * Klasse für Ausdrücke mit Vorzeichen, z.B.: -1
 * 
 * @author Christoph Beckmann
 */

public class ASTPraefixExpression extends SimpleNode {
    public ASTPraefixExpression(int id) {
        super(id);
    }

    public ASTPraefixExpression(fsParser p, int id) {
        super(p, id);
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
        for (int i = 0; i < children.length; i++) {
            jjtGetChild(i).bakeComponents(ab);
        }

    }

    /* (non-Javadoc)
     * @see math4u2.parser.formula.parserNodes.SimpleNode#toString()
     */
    public String toString() {
        return jjtGetChild(0).toString()+jjtGetChild(1).toString();
    }

}