package math4u2.parser.formula.parserNodes;

import math4u2.view.formula.*;
import math4u2.parser.formula.*;

/* Generated By:JJTree: Do not edit this line. ASTVecmathDefinition.java */

/**
 * Klasse für Vektor- und Matrizenwerte
 * 
 * @author Christoph Beckmann
 */

public class ASTVecmathDefinition extends SimpleNode {
    public ASTVecmathDefinition(int id) {
        super(id);
    }

    public ASTVecmathDefinition(fsParser p, int id) {
        super(p, id);
    }

    public void setName(String symbol) {
        super.symbol = symbol;
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
    	FormulaRenderContext frc = ab.getRenderContext();
        MatrixBox bb = new MatrixBox(frc);
        int noCols = 0;
        int noRows = 0;
        if (symbol.indexOf("matrix")!=-1) {
            noRows = jjtGetNumChildren();
            noCols = jjtGetChild(0).jjtGetNumChildren();
        } else if (symbol.trim().equals("vektor")) {
            noRows = jjtGetChild(0).jjtGetNumChildren();
            noCols = 1;
        } else if (symbol.indexOf("dualvektor")!=-1) {
            noRows = 1;
            noCols = jjtGetChild(0).jjtGetNumChildren();
        }
        GridBox gb = new GridBox(frc, noCols, noRows);
        for (int i = 0; i < children.length; i++) {
            jjtGetChild(i).bakeComponents(gb);
        }
        bb.add(gb);
        ab.add(bb);
    }

    /* (non-Javadoc)
     * @see math4u2.parser.formula.parserNodes.SimpleNode#toString()
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        Node n;
        for (int i = 0; i < children.length; i++) {
            n = jjtGetChild(i);
            sb.append("[");
            for (int j = 0; j < n.jjtGetNumChildren(); j++) {
                sb.append(n.jjtGetChild(j).toString());
                if(j<n.jjtGetNumChildren()-1)
                    sb.append(",");
            }
            sb.append("]");
            if(i<jjtGetNumChildren()-1)
                sb.append(",");
        }
        return symbol+"("+sb.toString()+")";
    }

}