/* Generated By:JJTree: Do not edit this line. ASTVecmathSymbol.java */

package math4u2.parser.formula.parserNodes;

import math4u2.view.formula.*;
import math4u2.view.layout.IndexLayout;
import math4u2.parser.formula.*;

/**
 * Klasse für Vektor- und Matrizenvariablen
 * 
 * @author Christoph Beckmann
 */
public class ASTVecmathSymbol extends SimpleNode {
    public ASTVecmathSymbol(int id) {
        super(id);
    }

    public ASTVecmathSymbol(fsParser p, int id) {
        super(p, id);
    }

    public void setName(String symbol) {
        super.symbol = symbol;
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.formula.AtomicBox)
     */
    public void bakeComponents(AtomicBox ab) {
    	FormulaRenderContext frc = ab.getRenderContext();
        IndexedBox ib = new IndexedBox(frc);
        String underline = "";
        if (symbol.indexOf("vektor")!=-1) {
            underline = "$quer";
        } else if (symbol.indexOf("matrix")!=-1) {
            underline = "\u2017";
        }
        ib.add(new OrdBox(frc, ((SimpleNode) jjtGetChild(0)).symbol),
                IndexLayout.CENTER);
        DecorationBox decoBox= new DecorationBox(frc,underline);
        
        ib.add(decoBox, IndexLayout.BOTTOM);
        ab.add(ib);

    }

    /* (non-Javadoc)
     * @see math4u2.parser.formula.parserNodes.SimpleNode#toString()
     */
    public String toString() {
        return symbol+ jjtGetChild(0).toString();
    }

}