/* Generated By:JJTree: Do not edit this line. ASTBrackets.java */

package math4u2.parser.formulaold.parserNodes;

import math4u2.view.formula.*;
import math4u2.view.formula.AtomicBox;
import math4u2.parser.formulaold.*;

/**
 * Klasse für runde Klammern.
 * 
 * @author Christoph Beckmann
 *  
 */

public class ASTBrackets extends SimpleNode {
    public ASTBrackets(int id) {
        super(id);
    }

    public ASTBrackets(fsParser p, int id) {
        super(p, id);
    }

    public void setName(String symbol) {
        super.symbol = symbol;
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
        byte type=BracketedBox.TYPE_PARENTHESE;
        if(symbol.equals("|")){
            type=BracketedBox.TYPE_ABS;
        }
    	BracketedBox bb = new BracketedBox(ab.getRenderContext(),type);
        jjtGetChild(0).bakeComponents(bb);
        ab.add(bb);

    }

}