/* Generated By:JJTree: Do not edit this line. ASTDiv.java */

package math4u2.parser.formulaold.parserNodes;

import math4u2.view.formula.*;
import math4u2.parser.formulaold.*;
import math4u2.view.formula.AtomicBox;
/**
 * Klasse für Brüche.
 * 
 * @author Christoph Beckmann
 *  
 */

public class ASTDiv extends SimpleNode {

    public ASTDiv(int id) {
        super(id);
    }

    public ASTDiv(fsParser p, int id) {
        super(p, id);
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
        InnerBox ib = new InnerBox(ab.getRenderContext());
        Node n0 = jjtGetChild(0);
        if (n0 instanceof ASTBrackets) {
            this.children[0] = n0.jjtGetChild(0);
            this.children[0].jjtSetParent(this);
        }
        Node n1 = jjtGetChild(1);
        if (n1 instanceof ASTBrackets) {
            this.children[1] = n1.jjtGetChild(0);
            this.children[1].jjtSetParent(this);
        }
        ContainerBox cb0 = new ContainerBox(ab.getRenderContext());
        jjtGetChild(0).bakeComponents(cb0);
        ContainerBox cb1 = new ContainerBox(ab.getRenderContext());
        jjtGetChild(1).bakeComponents(cb1);
        ib.add(cb0);
        ib.add(cb1);
        ab.add(ib);

    }

}