/* Generated By:JJTree: Do not edit this line. ASTIndexedExpression.java */

package math4u2.parser.formulaold.parserNodes;

import math4u2.view.formula.*;
import math4u2.view.layout.IndexLayout;
import math4u2.parser.formulaold.*;
import math4u2.view.formula.AtomicBox;
/**
 * Klasse für Terme mit Index.
 * 
 * @author Christoph Beckmann
 *  
 */

public class ASTIndexedExpression extends SimpleNode {
    public ASTIndexedExpression(int id) {
        super(id);
    }

    public ASTIndexedExpression(fsParser p, int id) {
        super(p, id);
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
        IndexedBox ib = new IndexedBox(ab.getRenderContext());
        ContainerBox cb0 = new ContainerBox(ab.getRenderContext());
        ContainerBox cb1 = new ContainerBox(ab.getRenderContext());
        jjtGetChild(0).bakeComponents(cb0);
        jjtGetChild(1).bakeComponents(cb1);
        ib.add(cb0, IndexLayout.CENTER);
        ib.add(cb1, IndexLayout.RIGHT_BOTTOM);
        ab.add(ib);

    }

}