/* Generated By:JJTree: Do not edit this line. ASTIndeces.java */

package math4u2.parser.formulaold.parserNodes;

import math4u2.view.formula.*;
import math4u2.parser.formulaold.*;
import math4u2.view.formula.AtomicBox;
/**
 * Klasse dient als Vaterknoten von ein oder mehrer Indeces.
 * 
 * @author Christoph Beckmann
 *  
 */

public class ASTIndeces extends SimpleNode {
    public ASTIndeces(int id) {
        super(id);
    }

    public ASTIndeces(fsParser p, int id) {
        super(p, id);
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
        for (int i = 0; i < children.length; i++) {
            jjtGetChild(i).bakeComponents(ab);
            if (i != children.length - 1)
                ab.add(new OrdBox(ab.getRenderContext(), ","));
        }
    }

}