package math4u2.parser.formulaold.parserNodes;

import math4u2.view.formula.*;
import math4u2.parser.formulaold.*;
import math4u2.view.formula.AtomicBox;
/* Generated By:JJTree: Do not edit this line. ASTListedExpressions.java */

public class ASTListedExpressions extends SimpleNode {
    public ASTListedExpressions(int id) {
        super(id);
    }

    public ASTListedExpressions(fsParser p, int id) {
        super(p, id);
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
        for (int i = 0; i < children.length; i++) {
            jjtGetChild(i).bakeComponents(ab);
            if (i != children.length - 1) {
            	FormulaRenderContext frc = ab.getRenderContext();
                ab.add(new OrdBox(frc, ","));
                ab.add(new EmptyBox(frc, 3f, 1f));
            }
        }

    }

}