package math4u2.parser.formulaold.parserNodes;

import math4u2.view.formula.*;
import math4u2.parser.formulaold.*;
import math4u2.view.formula.AtomicBox;
/* Generated By:JJTree: Do not edit this line. ASTNumber.java */

/**
 * Klasse für Zahlwerte
 * 
 * @author Christoph Beckmann
 */

public class ASTNumber extends SimpleNode {

    public ASTNumber(int id) {
        super(id);
    }

    public ASTNumber(fsParser p, int id) {
        super(p, id);
    }

    public void setName(String symbol) {
        super.symbol = symbol;
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
    	OrdBox numberBox = new OrdBox(ab.getRenderContext(), symbol);
        ab.add(numberBox);
    }

}