package math4u2.parser.formulaold.parserNodes;

import math4u2.view.formula.*;
import math4u2.parser.formulaold.*;
import math4u2.view.formula.AtomicBox;
/* Generated By:JJTree: Do not edit this line. ASTNormalFunction.java */

/**
 * Klasse für alle mathematischen Operationen, die in der Darstellung immer vom
 * Schema "Operand Operator Operand" sind.
 * 
 * @author Christoph Beckmann
 */

public class ASTNormalExpression extends SimpleNode {
    public ASTNormalExpression(int id) {
        super(id);
    }

    public ASTNormalExpression(fsParser p, int id) {
        super(p, id);
    }

    public void setName(String symbol) {
        super.symbol = symbol;
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
        this.jjtGetChild(0).bakeComponents(ab);
        ab.add(new BinBox(ab.getRenderContext(), symbol));
        this.jjtGetChild(1).bakeComponents(ab);

    }
}