package math4u2.parser.formulaold.parserNodes;

import math4u2.parser.formulaold.*;
import math4u2.view.formula.AtomicBox;
/* Generated By:JJTree: Do not edit this line. ASTNormalFunction.java */

/**
 * Klasse für Funktionen, die vom Benutzer benannt werden. Z.B.: f(x),
 * meineFunktion(x)
 * 
 * @author Christoph Beckmann
 */

public class ASTNormalFunction extends SimpleNode {

    public ASTNormalFunction(int id) {
        super(id);
    }

    public ASTNormalFunction(fsParser p, int id) {
        super(p, id);
    }


    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.formula.AtomicBox)
     */
    public void bakeComponents(AtomicBox ab) {
//        jjtGetChild(0).bakeComponents(ab);
//        BracketedBox bb = new BracketedBox(ab.getRenderContext());
//        jjtGetChild(1).bakeComponents(bb);
//        ab.add(bb);
        for(int i =0; i<jjtGetNumChildren();i++){
            jjtGetChild(i).bakeComponents(ab);
        }
    }

}