package math4u2.parser.formulaold.parserNodes;

import math4u2.view.formula.*;
import math4u2.parser.formulaold.*;
import math4u2.view.formula.AtomicBox;
/* Generated By:JJTree: Do not edit this line. ASTNabla.java */

public class ASTNabla extends SimpleNode {
    public ASTNabla(int id) {
        super(id);
    }

    public ASTNabla(fsParser p, int id) {
        super(p, id);
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
        ab.add(new OpBox(ab.getRenderContext(), "&nabla;"));

    }

}