package math4u2.parser.formulaold.parserNodes;

import math4u2.parser.formulaold.*;
import math4u2.view.formula.AtomicBox;
/* Generated By:JJTree: Do not edit this line. ASTStart.java */

/**
 * Klasse für den Startknoten
 * 
 * @author Christoph Beckmann
 */

public class ASTStart extends SimpleNode {
    public ASTStart(int id) {
        super(id);
    }

    public ASTStart(fsParser p, int id) {
        super(p, id);
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
        jjtGetChild(0).bakeComponents(ab);

    }

}