package math4u2.parser.formulaold.parserNodes;

import math4u2.view.formula.OrdBox;
import math4u2.parser.formulaold.*;
import math4u2.view.formula.AtomicBox;
/* Generated By:JJTree: Do not edit this line. ASTSymbol.java */

/**
 * Klasse für Symbole (griechische etc.)
 * 
 * @author Christoph Beckmann
 */

public class ASTSymbol extends SimpleNode {

	public ASTSymbol(int id) {
        super(id);
    }

    public ASTSymbol(fsParser p, int id) {
        super(p, id);
    }

    public void setName(String symbol) {
        super.symbol = symbol;
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.parser.Node)
     */
    public void bakeComponents(AtomicBox ab) {
    	OrdBox ob = new OrdBox(ab.getRenderContext(), symbol);
        ab.add(ob);
    }
}