/* Generated By:JJTree: Do not edit this line. ASTVecmathSymbol.java */

package math4u2.parser.formulaold.parserNodes;

import math4u2.view.formula.*;
import math4u2.view.layout.IndexLayout;
import math4u2.parser.formulaold.*;
import math4u2.view.formula.AtomicBox;
import math4u2.view.formula.FormulaRenderContext;

/**
 * Klasse für Vektor- und Matrizenvariablen
 * 
 * @author Christoph Beckmann
 */
public class ASTVecmathSymbol extends SimpleNode {
    public ASTVecmathSymbol(int id) {
        super(id);
    }

    public ASTVecmathSymbol(fsParser p, int id) {
        super(p, id);
    }

    public void setName(String symbol) {
        super.symbol = symbol;
    }

    /*
     * (non-Javadoc)
     * 
     * @see math4u2.view.parser.SimpleNode#bakeComponents(math4u2.view.formula.AtomicBox)
     */
    public void bakeComponents(AtomicBox ab) {
    	FormulaRenderContext frc = ab.getRenderContext();
        IndexedBox ib = new IndexedBox(frc);
        String underline = "";
        if (symbol.equals("<vektor>") || symbol.equals("<dualvektor>")) {
            underline = "-";
        } else if (symbol.equals("<matrix>")) {
            underline = "=";
        }
        ib.add(new OrdBox(frc, ((SimpleNode) jjtGetChild(0)).symbol),
                IndexLayout.CENTER);
        ib.add(new OrdBox(frc, underline), IndexLayout.BOTTOM);
        ab.add(ib);

    }

}