/* Generated By:JJTree&JavaCC: Do not edit this line. fsParserConstants.java */
package math4u2.parser.formulaold;

public interface fsParserConstants {

  int EOF = 0;
  int RELATIONSYMBOL = 7;
  int ARROW = 8;
  int REL_STRING_INFIX = 9;
  int ADDITIONSYMBOL = 10;
  int ADD_STRING = 11;
  int MULTIPLICATIONSYMBOL = 12;
  int MULT = 13;
  int MULT_STRING = 14;
  int DIVIDE = 15;
  int POSTFIX = 16;
  int STRING_PREFIX = 17;
  int ROOT = 18;
  int SQRT = 19;
  int SUM = 20;
  int INT = 21;
  int PROD = 22;
  int DERIVE = 23;
  int PDERIVE = 24;
  int EXIST = 25;
  int FORALL = 26;
  int MATHFUNCTION = 27;
  int LOG = 28;
  int FAC = 29;
  int EXPO = 30;
  int VECMATH = 31;
  int MATRIX = 32;
  int VECTOR = 33;
  int DUALVEKTOR = 34;
  int UNDEFVECTOR = 35;
  int UNDEFMATRIX = 36;
  int FLOAT_LITERAL = 37;
  int INTEGER_LITERAL = 38;
  int DIGIT = 39;
  int INFIN = 40;
  int EULER = 41;
  int PI = 42;
  int SYMBOL = 43;
  int GR_LETTER_LC = 44;
  int GR_LETTER_UC = 45;
  int NABLA = 46;
  int IDENTIFIER = 47;
  int LETTER = 48;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<RELATIONSYMBOL>",
    "<ARROW>",
    "<REL_STRING_INFIX>",
    "<ADDITIONSYMBOL>",
    "<ADD_STRING>",
    "<MULTIPLICATIONSYMBOL>",
    "\"*\"",
    "<MULT_STRING>",
    "\"/\"",
    "<POSTFIX>",
    "<STRING_PREFIX>",
    "\"root\"",
    "\"sqrt\"",
    "\"sum\"",
    "\"int\"",
    "\"prod\"",
    "\"derive\"",
    "\"pderive\"",
    "\"exist\"",
    "\"forall\"",
    "<MATHFUNCTION>",
    "\"log\"",
    "\"fac\"",
    "\"expo\"",
    "<VECMATH>",
    "\"matrix\"",
    "\"vektor\"",
    "\"dualvektor\"",
    "<UNDEFVECTOR>",
    "\"<matrix(\"",
    "<FLOAT_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DIGIT>",
    "\"&infin;\"",
    "\"e\"",
    "\"&pi;\"",
    "<SYMBOL>",
    "<GR_LETTER_LC>",
    "<GR_LETTER_UC>",
    "\"&nabla;\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "\":=\"",
    "\"^\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\"<vektor>\"",
    "\"<dualvektor>\"",
    "\"<matrix>\"",
    "\")>\"",
  };

}
