/* Generated By:JJTree&JavaCC: Do not edit this line. fsParser.java */
package math4u2.parser.formulaold;

import java.util.*;
import math4u2.parser.formulaold.parserNodes.*;
import math4u2.controller.*;

public class fsParser/*@bgen(jjtree)*/implements fsParserTreeConstants, fsParserConstants {/*@bgen(jjtree)*/
  protected JJTfsParserState jjtree = new JJTfsParserState();private Map modifierMap= new HashMap();
        private Broker broker;
        public static void main(String args[]) {}

        public void setModifierMap(Map modifierMap) {
        this.modifierMap= modifierMap;
    }

    public Map getModifierMap() {
        return modifierMap;
    }

    public Node parse(Broker broker) throws ParseException{
        this.broker=broker;
        return Start();
    }

  final public ASTStart Start() throws ParseException {
                    /*@bgen(jjtree) Start */
  ASTStart jjtn000 = new ASTStart(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Expression();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

/*
 * Ein Ausdruck kann sein
 * - Definition wie f(x):=
 * - Relation wie x+3 = 2*y - 4
 */
  final public void Expression() throws ParseException {
    if (jj_2_1(2147483647)) {
      Definition();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ADDITIONSYMBOL:
      case ROOT:
      case SQRT:
      case SUM:
      case INT:
      case PROD:
      case DERIVE:
      case PDERIVE:
      case EXIST:
      case FORALL:
      case MATHFUNCTION:
      case LOG:
      case FAC:
      case EXPO:
      case VECMATH:
      case UNDEFVECTOR:
      case UNDEFMATRIX:
      case FLOAT_LITERAL:
      case INTEGER_LITERAL:
      case INFIN:
      case EULER:
      case PI:
      case SYMBOL:
      case NABLA:
      case IDENTIFIER:
      case 52:
      case 59:
      case 60:
      case 61:
      case 62:
        RelationExpression();
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

/*
 * eine Definition ist gekennzeichnet durch ein ":="
 */
  final public void Definition() throws ParseException {
          ASTNormalExpression jjtn001 = new ASTNormalExpression(JJTNORMALEXPRESSION);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
    try {
      FunctionExpression();
      jj_consume_token(49);
      RelationExpression();
                  jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
                  jjtc001 = false;
                        jjtn001.setName(":=");
    } catch (Throwable jjte001) {
          if (jjtc001) {
            jjtree.clearNodeScope(jjtn001);
            jjtc001 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte001 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte001;}
          }
          if (jjte001 instanceof ParseException) {
            {if (true) throw (ParseException)jjte001;}
          }
          {if (true) throw (Error)jjte001;}
    } finally {
          if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
          }
    }
  }

/*
 * eine Relation besteht aus:
 * - min. zwei Ausdrücken mit Operatoren deren Bindungsstärke nicht höher als die der Addition
 * - zwischen zwei Ausdrücken steht ein Relationszeichen: <, >, =, ...
 */
  final public void RelationExpression() throws ParseException {
        Token symbol;
    AdditiveExpression();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case RELATIONSYMBOL:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      symbol = jj_consume_token(RELATIONSYMBOL);
      AdditiveExpression();
                          ASTNormalExpression jjtn001 = new ASTNormalExpression(JJTNORMALEXPRESSION);
                          boolean jjtc001 = true;
                          jjtree.openNodeScope(jjtn001);
      try {
                                  jjtree.closeNodeScope(jjtn001,  2);
                                  jjtc001 = false;
                                        jjtn001.setName(symbol.image);
      } finally {
                          if (jjtc001) {
                            jjtree.closeNodeScope(jjtn001,  2);
                          }
      }
    }
  }

/*
 * eine Addition besteht aus:
 * - min. zwei Ausdrücken mit Operatoren deren Bindungsstärke nicht höher als die der Multiplikation
 * - dem additionszeichen: + oder - oder +- zwischen jeweils zwei Ausdrücken
 * - der erste term kann ein vorzeichen haben
 */
  final public void AdditiveExpression() throws ParseException {
        Token symbol;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ADDITIONSYMBOL:
      PraefixExpression();
      break;
    case ROOT:
    case SQRT:
    case SUM:
    case INT:
    case PROD:
    case DERIVE:
    case PDERIVE:
    case EXIST:
    case FORALL:
    case MATHFUNCTION:
    case LOG:
    case FAC:
    case EXPO:
    case VECMATH:
    case UNDEFVECTOR:
    case UNDEFMATRIX:
    case FLOAT_LITERAL:
    case INTEGER_LITERAL:
    case INFIN:
    case EULER:
    case PI:
    case SYMBOL:
    case NABLA:
    case IDENTIFIER:
    case 52:
    case 59:
    case 60:
    case 61:
    case 62:
      MultiplicativeExpression();
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ADDITIONSYMBOL:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      symbol = jj_consume_token(ADDITIONSYMBOL);
      MultiplicativeExpression();
                  ASTNormalExpression jjtn001 = new ASTNormalExpression(JJTNORMALEXPRESSION);
                  boolean jjtc001 = true;
                  jjtree.openNodeScope(jjtn001);
      try {
                          jjtree.closeNodeScope(jjtn001,  2);
                          jjtc001 = false;
                                jjtn001.setName(symbol.image);
      } finally {
                  if (jjtc001) {
                    jjtree.closeNodeScope(jjtn001,  2);
                  }
      }
    }
  }

/*
 * Eine PraefixExpression hat zwei kinder
 * - das Praefix
 * - einem mult-Ausdruck 
 */
  final public void PraefixExpression() throws ParseException {
                            /*@bgen(jjtree) PraefixExpression */
  ASTPraefixExpression jjtn000 = new ASTPraefixExpression(JJTPRAEFIXEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Praefix();
      MultiplicativeExpression();
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

/*
 * ein PraefixOperator wie:  "-" kann auch ein "+" sein. 
 */
  final public void Praefix() throws ParseException {
                  /*@bgen(jjtree) Praefix */
        ASTPraefix jjtn000 = new ASTPraefix(JJTPRAEFIX);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token symbol;
    try {
      symbol = jj_consume_token(ADDITIONSYMBOL);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                jjtn000.setName(symbol.image);
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

/*
 * eine Multiplikation besteht aus:
 * - min zwei Ausdrücken mit Operatoren deren Bindungsstärke nicht höher als Division
 * - dem multiplikationszeichen zwischen jeweils 2 Operanden
 */
  final public void MultiplicativeExpression() throws ParseException {
        Token symbol;
    DivisiveExpression();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLICATIONSYMBOL:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      symbol = jj_consume_token(MULTIPLICATIONSYMBOL);
      DivisiveExpression();
                  ASTNormalExpression jjtn001 = new ASTNormalExpression(JJTNORMALEXPRESSION);
                  boolean jjtc001 = true;
                  jjtree.openNodeScope(jjtn001);
      try {
                          jjtree.closeNodeScope(jjtn001,  2);
                          jjtc001 = false;
                                jjtn001.setName(symbol.image);
      } finally {
                  if (jjtc001) {
                    jjtree.closeNodeScope(jjtn001,  2);
                  }
      }
    }
  }

/*
 * eine Division wird extra behandelt 
 * um einen Ausdruck wie 3*4/5 wie 3*(4/5) darzustellen 
 * die 3 steht so vor dem bruch
 */
  final public void DivisiveExpression() throws ParseException {
    ExponentialExpression();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DIVIDE:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
      jj_consume_token(DIVIDE);
                           ASTDiv jjtn001 = new ASTDiv(JJTDIV);
                           boolean jjtc001 = true;
                           jjtree.openNodeScope(jjtn001);
      try {
        ExponentialExpression();
      } catch (Throwable jjte001) {
                           if (jjtc001) {
                             jjtree.clearNodeScope(jjtn001);
                             jjtc001 = false;
                           } else {
                             jjtree.popNode();
                           }
                           if (jjte001 instanceof RuntimeException) {
                             {if (true) throw (RuntimeException)jjte001;}
                           }
                           if (jjte001 instanceof ParseException) {
                             {if (true) throw (ParseException)jjte001;}
                           }
                           {if (true) throw (Error)jjte001;}
      } finally {
                           if (jjtc001) {
                             jjtree.closeNodeScope(jjtn001,  2);
                           }
      }
    }
  }

/*
 * Ein exponentieller Ausdruck ist gekennzeichnet durch:
 * - min zwei Ausdrücken ohne Präfix- und Infixoperatoren
 * - ein Dach "^" zwischen jeweils zwei Ausdrücken
 */
  final public void ExponentialExpression() throws ParseException {
    PostfixExpression();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 50:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_5;
      }
      jj_consume_token(50);
                      ASTExpo jjtn001 = new ASTExpo(JJTEXPO);
                      boolean jjtc001 = true;
                      jjtree.openNodeScope(jjtn001);
      try {
        PostfixExpression();
      } catch (Throwable jjte001) {
                      if (jjtc001) {
                        jjtree.clearNodeScope(jjtn001);
                        jjtc001 = false;
                      } else {
                        jjtree.popNode();
                      }
                      if (jjte001 instanceof RuntimeException) {
                        {if (true) throw (RuntimeException)jjte001;}
                      }
                      if (jjte001 instanceof ParseException) {
                        {if (true) throw (ParseException)jjte001;}
                      }
                      {if (true) throw (Error)jjte001;}
      } finally {
                      if (jjtc001) {
                        jjtree.closeNodeScope(jjtn001,  2);
                      }
      }
    }
  }

/*
*Eine Postfix Expression ist gekennzeichnet durch: 
*- einen Term,ohne Infix- und Praefixoperatoren
* -einem Postfixoperator
*/
  final public void PostfixExpression() throws ParseException {
          ASTPostfixExpression jjtn001 = new ASTPostfixExpression(JJTPOSTFIXEXPRESSION);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
    try {
      if (jj_2_2(2147483647)) {
        NablaExpression();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ROOT:
        case SQRT:
        case SUM:
        case INT:
        case PROD:
        case DERIVE:
        case PDERIVE:
        case EXIST:
        case FORALL:
        case MATHFUNCTION:
        case LOG:
        case FAC:
        case EXPO:
        case VECMATH:
        case UNDEFVECTOR:
        case UNDEFMATRIX:
        case FLOAT_LITERAL:
        case INTEGER_LITERAL:
        case INFIN:
        case EULER:
        case PI:
        case SYMBOL:
        case NABLA:
        case IDENTIFIER:
        case 52:
        case 59:
        case 60:
        case 61:
        case 62:
          FunctionExpression();
          break;
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case POSTFIX:
        Postfix();
        break;
      default:
        jj_la1[8] = jj_gen;
        ;
      }
    } catch (Throwable jjte001) {
          if (jjtc001) {
            jjtree.clearNodeScope(jjtn001);
            jjtc001 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte001 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte001;}
          }
          if (jjte001 instanceof ParseException) {
            {if (true) throw (ParseException)jjte001;}
          }
          {if (true) throw (Error)jjte001;}
    } finally {
          if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
          }
    }
  }

/*
 * ein Postfix operator wie "!" (Fakultät)
*/
  final public void Postfix() throws ParseException {
                  /*@bgen(jjtree) Postfix */
        ASTPostfix jjtn000 = new ASTPostfix(JJTPOSTFIX);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token symbol;
    try {
      symbol = jj_consume_token(POSTFIX);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                jjtn000.setName(symbol.image);
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

/*
 * Ein Ausdruck mit dem Nabla-symbol
 * Nabla kann vor , hinter einem Ausdruck und alleine stehen
 */
  final public void NablaExpression() throws ParseException {
                          /*@bgen(jjtree) NablaExpression */
  ASTNablaExpression jjtn000 = new ASTNablaExpression(JJTNABLAEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      FunctionExpression();
      Nabla();
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

/*
 * der Nabla-knoten
 */
  final public void Nabla() throws ParseException {
                /*@bgen(jjtree) Nabla */
  ASTNabla jjtn000 = new ASTNabla(JJTNABLA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(NABLA);
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  final public void FunctionExpression() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case UNDEFVECTOR:
    case UNDEFMATRIX:
    case SYMBOL:
    case NABLA:
    case IDENTIFIER:
    case 60:
    case 61:
    case 62:
      MethodPath();
      break;
    case MATHFUNCTION:
    case LOG:
      MathFunction();
      break;
    case SUM:
    case INT:
    case PROD:
    case DERIVE:
    case PDERIVE:
    case EXIST:
    case FORALL:
      SpecialFunction();
      break;
    case FAC:
    case EXPO:
      DoubleFunction();
      break;
    case ROOT:
    case SQRT:
      Root();
      break;
    case VECMATH:
      VecmathDefinition();
      break;
    case FLOAT_LITERAL:
    case INTEGER_LITERAL:
    case INFIN:
    case EULER:
    case PI:
      Number();
      break;
    case 52:
    case 59:
      Brackets();
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/*
 * eine eigens definierte Funktion wie f(x), kann auch einen index haben f[1](x)
*/
  final public void MethodPath() throws ParseException {
    if (jj_2_3(2147483647)) {
                          ASTNormalFunction jjtn001 = new ASTNormalFunction(JJTNORMALFUNCTION);
                          boolean jjtc001 = true;
                          jjtree.openNodeScope(jjtn001);
      try {
        IndexedExpression();

        label_6:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 52:
            ;
            break;
          default:
            jj_la1[10] = jj_gen;
            break label_6;
          }
          EvalStep();
        }
      } catch (Throwable jjte001) {
                          if (jjtc001) {
                            jjtree.clearNodeScope(jjtn001);
                            jjtc001 = false;
                          } else {
                            jjtree.popNode();
                          }
                          if (jjte001 instanceof RuntimeException) {
                            {if (true) throw (RuntimeException)jjte001;}
                          }
                          if (jjte001 instanceof ParseException) {
                            {if (true) throw (ParseException)jjte001;}
                          }
                          {if (true) throw (Error)jjte001;}
      } finally {
                          if (jjtc001) {
                            jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
                          }
      }
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case UNDEFVECTOR:
      case UNDEFMATRIX:
      case SYMBOL:
      case NABLA:
      case IDENTIFIER:
      case 60:
      case 61:
      case 62:
                          ASTIndexedExpression jjtn003 = new ASTIndexedExpression(JJTINDEXEDEXPRESSION);
                          boolean jjtc003 = true;
                          jjtree.openNodeScope(jjtn003);
        try {
                                  ASTNormalFunction jjtn002 = new ASTNormalFunction(JJTNORMALFUNCTION);
                                  boolean jjtc002 = true;
                                  jjtree.openNodeScope(jjtn002);
          try {
            Variable();
            label_7:
            while (true) {
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case 52:
                ;
                break;
              default:
                jj_la1[11] = jj_gen;
                break label_7;
              }
              EvalStep();
            }
          } catch (Throwable jjte002) {
                                  if (jjtc002) {
                                    jjtree.clearNodeScope(jjtn002);
                                    jjtc002 = false;
                                  } else {
                                    jjtree.popNode();
                                  }
                                  if (jjte002 instanceof RuntimeException) {
                                    {if (true) throw (RuntimeException)jjte002;}
                                  }
                                  if (jjte002 instanceof ParseException) {
                                    {if (true) throw (ParseException)jjte002;}
                                  }
                                  {if (true) throw (Error)jjte002;}
          } finally {
                                  if (jjtc002) {
                                    jjtree.closeNodeScope(jjtn002, jjtree.nodeArity() > 1);
                                  }
          }
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 51:
          case 57:
            Indeces();
            break;
          default:
            jj_la1[12] = jj_gen;
            ;
          }
        } catch (Throwable jjte003) {
                          if (jjtc003) {
                            jjtree.clearNodeScope(jjtn003);
                            jjtc003 = false;
                          } else {
                            jjtree.popNode();
                          }
                          if (jjte003 instanceof RuntimeException) {
                            {if (true) throw (RuntimeException)jjte003;}
                          }
                          if (jjte003 instanceof ParseException) {
                            {if (true) throw (ParseException)jjte003;}
                          }
                          {if (true) throw (Error)jjte003;}
        } finally {
                          if (jjtc003) {
                            jjtree.closeNodeScope(jjtn003, jjtree.nodeArity() > 1);
                          }
        }
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void KeyWordStep() throws ParseException {
          ASTIndexedExpression jjtn001 = new ASTIndexedExpression(JJTINDEXEDEXPRESSION);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
    try {
      jj_consume_token(51);
      Ident();
    } catch (Throwable jjte001) {
          if (jjtc001) {
            jjtree.clearNodeScope(jjtn001);
            jjtc001 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte001 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte001;}
          }
          if (jjte001 instanceof ParseException) {
            {if (true) throw (ParseException)jjte001;}
          }
          {if (true) throw (Error)jjte001;}
    } finally {
          if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, true);
          }
    }
  }

/*
 * Funktionen, wie: sin, cos, tan,...
*/
  final public void MathFunction() throws ParseException {
                       /*@bgen(jjtree) MathFunction */
        ASTMathFunction jjtn000 = new ASTMathFunction(JJTMATHFUNCTION);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token type;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MATHFUNCTION:
        type = jj_consume_token(MATHFUNCTION);
        jj_consume_token(52);
        AdditiveExpression();
        jj_consume_token(53);
        break;
      case LOG:
        type = jj_consume_token(LOG);
        TwoDigitFunction();
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                jjtn000.setName(type.image);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

/*
 * spezielle Funktionen sind sum(..), int(..), prod(..) usw.
*/
  final public void SpecialFunction() throws ParseException {
        Token symbol;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUM:
    case INT:
    case PROD:
          ASTSpecialFunction jjtn001 = new ASTSpecialFunction(JJTSPECIALFUNCTION);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SUM:
          symbol = jj_consume_token(SUM);
          Sum();
                          jjtree.closeNodeScope(jjtn001, true);
                          jjtc001 = false;
                                jjtn001.setName(symbol.image);
          break;
        case PROD:
          symbol = jj_consume_token(PROD);
          Prod();
                          jjtree.closeNodeScope(jjtn001, true);
                          jjtc001 = false;
                                jjtn001.setName(symbol.image);
          break;
        case INT:
          symbol = jj_consume_token(INT);
          Int();
                          jjtree.closeNodeScope(jjtn001, true);
                          jjtc001 = false;
                                jjtn001.setName(symbol.image);
          break;
        default:
          jj_la1[15] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte001) {
          if (jjtc001) {
            jjtree.clearNodeScope(jjtn001);
            jjtc001 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte001 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte001;}
          }
          if (jjte001 instanceof ParseException) {
            {if (true) throw (ParseException)jjte001;}
          }
          {if (true) throw (Error)jjte001;}
      } finally {
          if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, true);
          }
      }
      break;
    case DERIVE:
      Derive();
      break;
    case PDERIVE:
          ASTPDerive jjtn002 = new ASTPDerive(JJTPDERIVE);
          boolean jjtc002 = true;
          jjtree.openNodeScope(jjtn002);
      try {
        symbol = jj_consume_token(PDERIVE);
        PDerive();
                  jjtree.closeNodeScope(jjtn002, true);
                  jjtc002 = false;
                        jjtn002.setName(symbol.image);
      } catch (Throwable jjte002) {
          if (jjtc002) {
            jjtree.clearNodeScope(jjtn002);
            jjtc002 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte002 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte002;}
          }
          if (jjte002 instanceof ParseException) {
            {if (true) throw (ParseException)jjte002;}
          }
          {if (true) throw (Error)jjte002;}
      } finally {
          if (jjtc002) {
            jjtree.closeNodeScope(jjtn002, true);
          }
      }
      break;
    case EXIST:
      symbol = jj_consume_token(EXIST);
      Exist();
      break;
    case FORALL:
      symbol = jj_consume_token(FORALL);
      ForAll();
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void Sum() throws ParseException {
    jj_consume_token(52);
    FunctionExpression();
    jj_consume_token(54);
    AdditiveExpression();
    jj_consume_token(54);
    AdditiveExpression();
    jj_consume_token(54);
    AdditiveExpression();
    jj_consume_token(53);
  }

  final public void Prod() throws ParseException {
    jj_consume_token(52);
    FunctionExpression();
    jj_consume_token(54);
    AdditiveExpression();
    jj_consume_token(54);
    AdditiveExpression();
    jj_consume_token(54);
    AdditiveExpression();
    jj_consume_token(53);
  }

  final public void Derive() throws ParseException {
                 /*@bgen(jjtree) Derive */
        ASTDerive jjtn000 = new ASTDerive(JJTDERIVE);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token t;
    try {
      jj_consume_token(DERIVE);
      jj_consume_token(52);
      AdditiveExpression();
                jjtn000.setName("1");
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 54:
        jj_consume_token(54);
        t = jj_consume_token(INTEGER_LITERAL);
                        jjtn000.setName(t.image);
        break;
      default:
        jj_la1[17] = jj_gen;
        ;
      }
      jj_consume_token(53);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  final public void PDerive() throws ParseException {
    jj_consume_token(52);
    AdditiveExpression();
    jj_consume_token(54);
    FunctionExpression();
    jj_consume_token(54);
    FunctionExpression();
    jj_consume_token(53);
  }

  final public void Int() throws ParseException {
    jj_consume_token(52);
    FunctionExpression();
    jj_consume_token(54);
    FunctionExpression();
    jj_consume_token(54);
    FunctionExpression();
    jj_consume_token(54);
    AdditiveExpression();
    jj_consume_token(53);
  }

// 3-stellige funktion schreibweise und parameter??
  final public void Exist() throws ParseException {
    jj_consume_token(52);
    FunctionExpression();
    jj_consume_token(54);
    FunctionExpression();
    jj_consume_token(54);
    FunctionExpression();
    jj_consume_token(53);
  }

// 3-stellige funktion schreibweise und parameter??
  final public void ForAll() throws ParseException {
    jj_consume_token(52);
    FunctionExpression();
    jj_consume_token(54);
    FunctionExpression();
    jj_consume_token(54);
    FunctionExpression();
    jj_consume_token(53);
  }

// body für 2-stellige Funktionen
  final public void TwoDigitFunction() throws ParseException {
    jj_consume_token(52);
    AdditiveExpression();
    jj_consume_token(54);
    AdditiveExpression();
    jj_consume_token(53);
  }

/**
 * Ausdrücke die sowohl durch OperationsZeichen als auch durch Funktionen erzeugt werden können
 * expo(..,..) und fac(..)
 */
  final public void DoubleFunction() throws ParseException {
        Token type;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FAC:
          ASTPostfixExpression jjtn003 = new ASTPostfixExpression(JJTPOSTFIXEXPRESSION);
          boolean jjtc003 = true;
          jjtree.openNodeScope(jjtn003);
      try {
        jj_consume_token(FAC);
        jj_consume_token(52);
                  ASTBrackets jjtn001 = new ASTBrackets(JJTBRACKETS);
                  boolean jjtc001 = true;
                  jjtree.openNodeScope(jjtn001);
        try {
          AdditiveExpression();
        } catch (Throwable jjte001) {
                  if (jjtc001) {
                    jjtree.clearNodeScope(jjtn001);
                    jjtc001 = false;
                  } else {
                    jjtree.popNode();
                  }
                  if (jjte001 instanceof RuntimeException) {
                    {if (true) throw (RuntimeException)jjte001;}
                  }
                  if (jjte001 instanceof ParseException) {
                    {if (true) throw (ParseException)jjte001;}
                  }
                  {if (true) throw (Error)jjte001;}
        } finally {
                  if (jjtc001) {
                    jjtree.closeNodeScope(jjtn001,  ( ( SimpleNode ) jjtree . peekNode ( ) ) . getId ( ) < 16);
                  }
        }
        jj_consume_token(53);
                  ASTPostfix jjtn002 = new ASTPostfix(JJTPOSTFIX);
                  boolean jjtc002 = true;
                  jjtree.openNodeScope(jjtn002);
        try {
                          jjtree.closeNodeScope(jjtn002, true);
                          jjtc002 = false;
                                jjtn002.setName("!");
        } finally {
                  if (jjtc002) {
                    jjtree.closeNodeScope(jjtn002, true);
                  }
        }
      } catch (Throwable jjte003) {
          if (jjtc003) {
            jjtree.clearNodeScope(jjtn003);
            jjtc003 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte003 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte003;}
          }
          if (jjte003 instanceof ParseException) {
            {if (true) throw (ParseException)jjte003;}
          }
          {if (true) throw (Error)jjte003;}
      } finally {
          if (jjtc003) {
            jjtree.closeNodeScope(jjtn003, true);
          }
      }
      break;
    case EXPO:
          ASTExpo jjtn006 = new ASTExpo(JJTEXPO);
          boolean jjtc006 = true;
          jjtree.openNodeScope(jjtn006);
      try {
        jj_consume_token(EXPO);
        jj_consume_token(52);
                  ASTBrackets jjtn004 = new ASTBrackets(JJTBRACKETS);
                  boolean jjtc004 = true;
                  jjtree.openNodeScope(jjtn004);
        try {
          AdditiveExpression();
        } catch (Throwable jjte004) {
                  if (jjtc004) {
                    jjtree.clearNodeScope(jjtn004);
                    jjtc004 = false;
                  } else {
                    jjtree.popNode();
                  }
                  if (jjte004 instanceof RuntimeException) {
                    {if (true) throw (RuntimeException)jjte004;}
                  }
                  if (jjte004 instanceof ParseException) {
                    {if (true) throw (ParseException)jjte004;}
                  }
                  {if (true) throw (Error)jjte004;}
        } finally {
                  if (jjtc004) {
                    jjtree.closeNodeScope(jjtn004,  ( ( SimpleNode ) jjtree . peekNode ( ) ) . getId ( ) < 16);
                  }
        }
        jj_consume_token(54);
                      ASTBrackets jjtn005 = new ASTBrackets(JJTBRACKETS);
                      boolean jjtc005 = true;
                      jjtree.openNodeScope(jjtn005);
        try {
          AdditiveExpression();
        } catch (Throwable jjte005) {
                      if (jjtc005) {
                        jjtree.clearNodeScope(jjtn005);
                        jjtc005 = false;
                      } else {
                        jjtree.popNode();
                      }
                      if (jjte005 instanceof RuntimeException) {
                        {if (true) throw (RuntimeException)jjte005;}
                      }
                      if (jjte005 instanceof ParseException) {
                        {if (true) throw (ParseException)jjte005;}
                      }
                      {if (true) throw (Error)jjte005;}
        } finally {
                      if (jjtc005) {
                        jjtree.closeNodeScope(jjtn005, true);
                      }
        }
        jj_consume_token(53);
      } catch (Throwable jjte006) {
          if (jjtc006) {
            jjtree.clearNodeScope(jjtn006);
            jjtc006 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte006 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte006;}
          }
          if (jjte006 instanceof ParseException) {
            {if (true) throw (ParseException)jjte006;}
          }
          {if (true) throw (Error)jjte006;}
      } finally {
          if (jjtc006) {
            jjtree.closeNodeScope(jjtn006, true);
          }
      }
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void Root() throws ParseException {
               /*@bgen(jjtree) Root */
  ASTRoot jjtn000 = new ASTRoot(JJTROOT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SQRT:
        jj_consume_token(SQRT);
        jj_consume_token(52);
        AdditiveExpression();
        jj_consume_token(53);
                  ASTNumber jjtn001 = new ASTNumber(JJTNUMBER);
                  boolean jjtc001 = true;
                  jjtree.openNodeScope(jjtn001);
        try {
                          jjtree.closeNodeScope(jjtn001, true);
                          jjtc001 = false;
                         jjtn001.setName("2");
        } finally {
                  if (jjtc001) {
                    jjtree.closeNodeScope(jjtn001, true);
                  }
        }
        break;
      case ROOT:
        jj_consume_token(ROOT);
        jj_consume_token(52);
        AdditiveExpression();
        jj_consume_token(54);
        AdditiveExpression();
        jj_consume_token(53);
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

/*
 * spezieller Ausdruck zur Definition von Vektoren und Matrizen 
*/
  final public void VecmathDefinition() throws ParseException {
                            /*@bgen(jjtree) VecmathDefinition */
        ASTVecmathDefinition jjtn000 = new ASTVecmathDefinition(JJTVECMATHDEFINITION);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);int test;
        int test2;
        Token type;
    try {
      type = jj_consume_token(VECMATH);
                jjtn000.setName(type.image);
      jj_consume_token(52);
      if (jj_2_4(2)) {
        jj_consume_token(55);
        test = Braces();
        jj_consume_token(56);
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 55:
          jj_consume_token(55);
          jj_consume_token(55);
          test = Braces();
          jj_consume_token(56);
          label_8:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case 54:
              ;
              break;
            default:
              jj_la1[20] = jj_gen;
              break label_8;
            }
            jj_consume_token(54);
            jj_consume_token(55);
            test2 = Braces();
            jj_consume_token(56);
                                        if (test != test2)
                                        {
                                                {if (true) throw new ParseException(
                                                        "Ungleiche Spalten bei Matrix in Zeile: " + token.next.beginLine);}
                                        }
          }
          jj_consume_token(56);
          break;
        default:
          jj_la1[21] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(53);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

/*
 * Ausdruck für alle funktionen mit mehreren parametern: z.b. f(x,y)
*/
  final public void EvalStep() throws ParseException {
          ASTBrackets jjtn002 = new ASTBrackets(JJTBRACKETS);
          boolean jjtc002 = true;
          jjtree.openNodeScope(jjtn002);
    try {
                  ASTListedExpressions jjtn001 = new ASTListedExpressions(JJTLISTEDEXPRESSIONS);
                  boolean jjtc001 = true;
                  jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(52);
        RelationExpression();
        label_9:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 54:
            ;
            break;
          default:
            jj_la1[22] = jj_gen;
            break label_9;
          }
          jj_consume_token(54);
          RelationExpression();
        }
        jj_consume_token(53);
      } catch (Throwable jjte001) {
                  if (jjtc001) {
                    jjtree.clearNodeScope(jjtn001);
                    jjtc001 = false;
                  } else {
                    jjtree.popNode();
                  }
                  if (jjte001 instanceof RuntimeException) {
                    {if (true) throw (RuntimeException)jjte001;}
                  }
                  if (jjte001 instanceof ParseException) {
                    {if (true) throw (ParseException)jjte001;}
                  }
                  {if (true) throw (Error)jjte001;}
      } finally {
                  if (jjtc001) {
                    jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
                  }
      }
    } catch (Throwable jjte002) {
          if (jjtc002) {
            jjtree.clearNodeScope(jjtn002);
            jjtc002 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte002 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte002;}
          }
          if (jjte002 instanceof ParseException) {
            {if (true) throw (ParseException)jjte002;}
          }
          {if (true) throw (Error)jjte002;}
    } finally {
          if (jjtc002) {
            jjtree.closeNodeScope(jjtn002, true);
          }
    }
  }

/*
 * wird zur Definition von Vektoren und Matrizen verwendet "{...}"
 */
  final public int Braces() throws ParseException {
                /*@bgen(jjtree) Braces */
        ASTBraces jjtn000 = new ASTBraces(JJTBRACES);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);int counter= 1;
    try {
      RelationExpression();
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 54:
          ;
          break;
        default:
          jj_la1[23] = jj_gen;
          break label_10;
        }
        jj_consume_token(54);
        RelationExpression();
                        counter++;
      }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                {if (true) return counter;}
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

/*
 * Ausdruck für terme mit Index. Besteht aus:
 * - entweder einem geklammerten Ausdruck
 * - oder einer Variable
 * - und ein oder mehreren "[..]"- additiven Ausdrücken
 */
  final public void IndexedExpression() throws ParseException {
          ASTIndexedExpression jjtn001 = new ASTIndexedExpression(JJTINDEXEDEXPRESSION);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
    try {
      Variable();
      Indeces();
    } catch (Throwable jjte001) {
          if (jjtc001) {
            jjtree.clearNodeScope(jjtn001);
            jjtc001 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte001 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte001;}
          }
          if (jjte001 instanceof ParseException) {
            {if (true) throw (ParseException)jjte001;}
          }
          {if (true) throw (Error)jjte001;}
    } finally {
          if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
          }
    }
  }

/*
 * ein Indeces- Knoten
 */
  final public void Indeces() throws ParseException {
          ASTIndeces jjtn001 = new ASTIndeces(JJTINDECES);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
    try {
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 57:
          jj_consume_token(57);
          AdditiveExpression();
          label_12:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case 54:
              ;
              break;
            default:
              jj_la1[24] = jj_gen;
              break label_12;
            }
            jj_consume_token(54);
            AdditiveExpression();
          }
          jj_consume_token(58);
          break;
        case 51:
          jj_consume_token(51);
          Ident();
          break;
        default:
          jj_la1[25] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 51:
        case 57:
          ;
          break;
        default:
          jj_la1[26] = jj_gen;
          break label_11;
        }
      }
    } catch (Throwable jjte001) {
          if (jjtc001) {
            jjtree.clearNodeScope(jjtn001);
            jjtc001 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte001 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte001;}
          }
          if (jjte001 instanceof ParseException) {
            {if (true) throw (ParseException)jjte001;}
          }
          {if (true) throw (Error)jjte001;}
    } finally {
          if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, true);
          }
    }
  }

/*
 * ein geklammerter Ausdruck. sowohl "(...)" als auch "|...|"
 */
  final public void Brackets() throws ParseException {
                   /*@bgen(jjtree) Brackets */
        ASTBrackets jjtn000 = new ASTBrackets(JJTBRACKETS);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token symbol;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 52:
        symbol = jj_consume_token(52);
        Expression();
        jj_consume_token(53);
        break;
      case 59:
        symbol = jj_consume_token(59);
        AdditiveExpression();
        jj_consume_token(59);
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                jjtn000.setName(symbol.image);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

/*
 * eine Variable kann sowohl ein Identifier als auch ein symbol wie gr. Buchstabe sein
 * außerdem kann es ein Nabla sein oder ein Nabla und eine variable.
 */
  final public void Variable() throws ParseException {
          ASTNablaExpression jjtn001 = new ASTNablaExpression(JJTNABLAEXPRESSION);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NABLA:
        Nabla();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case UNDEFVECTOR:
        case UNDEFMATRIX:
        case SYMBOL:
        case IDENTIFIER:
        case 60:
        case 61:
        case 62:
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IDENTIFIER:
            Ident();
            break;
          case SYMBOL:
            Symbol();
            break;
          case UNDEFVECTOR:
            UndefinedVector();
            break;
          case 60:
          case 61:
          case 62:
            VecmathSymbol();
            break;
          case UNDEFMATRIX:
            UndefinedMatrix();
            break;
          default:
            jj_la1[28] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        default:
          jj_la1[29] = jj_gen;
          ;
        }
        break;
      case UNDEFVECTOR:
      case UNDEFMATRIX:
      case SYMBOL:
      case IDENTIFIER:
      case 60:
      case 61:
      case 62:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
          Ident();
          break;
        case SYMBOL:
          Symbol();
          break;
        case UNDEFVECTOR:
          UndefinedVector();
          break;
        case 60:
        case 61:
        case 62:
          VecmathSymbol();
          break;
        case UNDEFMATRIX:
          UndefinedMatrix();
          break;
        default:
          jj_la1[30] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte001) {
          if (jjtc001) {
            jjtree.clearNodeScope(jjtn001);
            jjtc001 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte001 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte001;}
          }
          if (jjte001 instanceof ParseException) {
            {if (true) throw (ParseException)jjte001;}
          }
          {if (true) throw (Error)jjte001;}
    } finally {
          if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
          }
    }
  }

  final public void VecmathSymbol() throws ParseException {
                        /*@bgen(jjtree) VecmathSymbol */
        ASTVecmathSymbol jjtn000 = new ASTVecmathSymbol(JJTVECMATHSYMBOL);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 60:
        t = jj_consume_token(60);
                        jjtn000.setName(t.image);
        break;
      case 61:
        t = jj_consume_token(61);
                        jjtn000.setName(t.image);
        break;
      case 62:
        t = jj_consume_token(62);
                        jjtn000.setName(t.image);
        break;
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Ident();
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  final public void UndefinedVector() throws ParseException {
                          /*@bgen(jjtree) UndefinedVector */
        ASTUndefinedVector jjtn000 = new ASTUndefinedVector(JJTUNDEFINEDVECTOR);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token t;
        Token t2;
    try {
      t = jj_consume_token(UNDEFVECTOR);
                jjtn000.setName(t.image);
                  ASTNumber jjtn001 = new ASTNumber(JJTNUMBER);
                  boolean jjtc001 = true;
                  jjtree.openNodeScope(jjtn001);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INTEGER_LITERAL:
          t2 = jj_consume_token(INTEGER_LITERAL);
          break;
        case IDENTIFIER:
          t2 = jj_consume_token(IDENTIFIER);
          break;
        default:
          jj_la1[33] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
                          jjtree.closeNodeScope(jjtn001, true);
                          jjtc001 = false;
                                jjtn001.setName(t2.image);
      } finally {
                  if (jjtc001) {
                    jjtree.closeNodeScope(jjtn001, true);
                  }
      }
      jj_consume_token(63);
      Ident();
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  //erstellt eine matrix mit werten vom Typ m[1][1],m[1][2],...,m[1][n],m[2][1],...m[n][k];
  final public void UndefinedMatrix() throws ParseException {
                          /*@bgen(jjtree) UndefinedMatrix */
        ASTUndefinedMatrix jjtn000 = new ASTUndefinedMatrix(JJTUNDEFINEDMATRIX);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token t;
    try {
      jj_consume_token(UNDEFMATRIX);
          ASTNumber jjtn001 = new ASTNumber(JJTNUMBER);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INTEGER_LITERAL:
          t = jj_consume_token(INTEGER_LITERAL);
          break;
        case IDENTIFIER:
          t = jj_consume_token(IDENTIFIER);
          break;
        default:
          jj_la1[34] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
                  jjtree.closeNodeScope(jjtn001, true);
                  jjtc001 = false;
                        jjtn001.setName(t.image);
      } finally {
          if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, true);
          }
      }
      jj_consume_token(54);
          ASTNumber jjtn002 = new ASTNumber(JJTNUMBER);
          boolean jjtc002 = true;
          jjtree.openNodeScope(jjtn002);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INTEGER_LITERAL:
          t = jj_consume_token(INTEGER_LITERAL);
          break;
        case IDENTIFIER:
          t = jj_consume_token(IDENTIFIER);
          break;
        default:
          jj_la1[35] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
                  jjtree.closeNodeScope(jjtn002, true);
                  jjtc002 = false;
                        jjtn002.setName(t.image);
      } finally {
          if (jjtc002) {
            jjtree.closeNodeScope(jjtn002, true);
          }
      }
      jj_consume_token(63);
      Ident();
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  final public void PointExpression() throws ParseException {
        Token t;
        String s;
          ASTIdent jjtn001 = new ASTIdent(JJTIDENT);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
    try {
      t = jj_consume_token(IDENTIFIER);
                        s=t.image;
      jj_consume_token(51);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER_LITERAL:
        t = jj_consume_token(INTEGER_LITERAL);
        break;
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
        break;
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                  jjtree.closeNodeScope(jjtn001, true);
                  jjtc001 = false;
                        s+="."+t.image;
                        jjtn001.setName(s);
    } finally {
          if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, true);
          }
    }
  }

  final public void Ident() throws ParseException {
                /*@bgen(jjtree) Ident */
        ASTIdent jjtn000 = new ASTIdent(JJTIDENT);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token t;
        String s;
    try {
      t = jj_consume_token(IDENTIFIER);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                jjtn000.setName(t.image);
                Map m = (Map)modifierMap.get(t.image);
                if(m!=null){
                        jjtn000.setModifier(m);
                        jjtn000.setBroker(broker);
                }
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  final public void Number() throws ParseException {
                 /*@bgen(jjtree) Number */
        ASTNumber jjtn000 = new ASTNumber(JJTNUMBER);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token symbol;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INFIN:
        symbol = jj_consume_token(INFIN);
        break;
      case EULER:
        symbol = jj_consume_token(EULER);
        break;
      case PI:
        symbol = jj_consume_token(PI);
        break;
      case FLOAT_LITERAL:
        symbol = jj_consume_token(FLOAT_LITERAL);
        break;
      case INTEGER_LITERAL:
        symbol = jj_consume_token(INTEGER_LITERAL);
        break;
      default:
        jj_la1[37] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                jjtn000.setName(symbol.image);
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  final public void Symbol() throws ParseException {
                 /*@bgen(jjtree) Symbol */
        ASTSymbol jjtn000 = new ASTSymbol(JJTSYMBOL);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token symbol;
    try {
      symbol = jj_consume_token(SYMBOL);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                jjtn000.setName(symbol.image);
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  final private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  final private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  final private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  final private boolean jj_3R_60() {
    if (jj_scan_token(PDERIVE)) return true;
    if (jj_3R_91()) return true;
    return false;
  }

  final private boolean jj_3R_112() {
    if (jj_scan_token(54)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  final private boolean jj_3R_107() {
    if (jj_scan_token(54)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  final private boolean jj_3R_89() {
    if (jj_scan_token(INT)) return true;
    if (jj_3R_105()) return true;
    return false;
  }

  final private boolean jj_3R_59() {
    if (jj_3R_90()) return true;
    return false;
  }

  final private boolean jj_3R_71() {
    if (jj_3R_97()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_98()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_88() {
    if (jj_scan_token(PROD)) return true;
    if (jj_3R_104()) return true;
    return false;
  }

  final private boolean jj_3R_16() {
    if (jj_3R_18()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_107()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_87() {
    if (jj_scan_token(SUM)) return true;
    if (jj_3R_103()) return true;
    return false;
  }

  final private boolean jj_3R_96() {
    if (jj_scan_token(ADDITIONSYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_37() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) return true;
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_58() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_87()) {
    jj_scanpos = xsp;
    if (jj_3R_88()) {
    jj_scanpos = xsp;
    if (jj_3R_89()) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_94() {
    if (jj_scan_token(54)) return true;
    if (jj_scan_token(55)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(56)) return true;
    return false;
  }

  final private boolean jj_3R_102() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_18()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_112()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_57() {
    if (jj_scan_token(LOG)) return true;
    if (jj_3R_86()) return true;
    return false;
  }

  final private boolean jj_3R_84() {
    if (jj_3R_102()) return true;
    return false;
  }

  final private boolean jj_3R_56() {
    if (jj_scan_token(MATHFUNCTION)) return true;
    if (jj_scan_token(52)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_81() {
    if (jj_scan_token(UNDEFMATRIX)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(38)) {
    jj_scanpos = xsp;
    if (jj_scan_token(47)) return true;
    }
    if (jj_scan_token(54)) return true;
    xsp = jj_scanpos;
    if (jj_scan_token(38)) {
    jj_scanpos = xsp;
    if (jj_scan_token(47)) return true;
    }
    if (jj_scan_token(63)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  final private boolean jj_3R_70() {
    if (jj_3R_96()) return true;
    if (jj_3R_71()) return true;
    return false;
  }

  final private boolean jj_3R_85() {
    if (jj_3R_21()) return true;
    return false;
  }

  final private boolean jj_3R_36() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) return true;
    }
    return false;
  }

  final private boolean jj_3R_45() {
    if (jj_scan_token(ADDITIONSYMBOL)) return true;
    if (jj_3R_71()) return true;
    return false;
  }

  final private boolean jj_3R_83() {
    if (jj_3R_102()) return true;
    return false;
  }

  final private boolean jj_3R_44() {
    if (jj_3R_71()) return true;
    return false;
  }

  final private boolean jj_3R_67() {
    if (jj_scan_token(55)) return true;
    if (jj_scan_token(55)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(56)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_94()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(56)) return true;
    return false;
  }

  final private boolean jj_3R_43() {
    if (jj_3R_70()) return true;
    return false;
  }

  final private boolean jj_3_4() {
    if (jj_scan_token(55)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(56)) return true;
    return false;
  }

  final private boolean jj_3_3() {
    if (jj_3R_15()) return true;
    return false;
  }

  final private boolean jj_3R_55() {
    if (jj_3R_20()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_84()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_3R_85()) jj_scanpos = xsp;
    return false;
  }

  final private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_45()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_79() {
    if (jj_scan_token(UNDEFVECTOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(38)) {
    jj_scanpos = xsp;
    if (jj_scan_token(47)) return true;
    }
    if (jj_scan_token(63)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  final private boolean jj_3R_54() {
    if (jj_3R_15()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_83()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_101() {
    if (jj_scan_token(62)) return true;
    return false;
  }

  final private boolean jj_3R_31() {
    if (jj_scan_token(RELATIONSYMBOL)) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  final private boolean jj_3R_40() {
    if (jj_scan_token(VECMATH)) return true;
    if (jj_scan_token(52)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) return true;
    }
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_100() {
    if (jj_scan_token(61)) return true;
    return false;
  }

  final private boolean jj_3R_35() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) return true;
    }
    return false;
  }

  final private boolean jj_3R_99() {
    if (jj_scan_token(60)) return true;
    return false;
  }

  final private boolean jj_3R_51() {
    if (jj_3R_81()) return true;
    return false;
  }

  final private boolean jj_3R_50() {
    if (jj_3R_80()) return true;
    return false;
  }

  final private boolean jj_3R_66() {
    if (jj_scan_token(ROOT)) return true;
    if (jj_scan_token(52)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_49() {
    if (jj_3R_79()) return true;
    return false;
  }

  final private boolean jj_3R_48() {
    if (jj_3R_78()) return true;
    return false;
  }

  final private boolean jj_3R_80() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_99()) {
    jj_scanpos = xsp;
    if (jj_3R_100()) {
    jj_scanpos = xsp;
    if (jj_3R_101()) return true;
    }
    }
    if (jj_3R_77()) return true;
    return false;
  }

  final private boolean jj_3R_18() {
    if (jj_3R_30()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_31()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_47() {
    if (jj_3R_77()) return true;
    return false;
  }

  final private boolean jj_3R_39() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) return true;
    }
    return false;
  }

  final private boolean jj_3R_65() {
    if (jj_scan_token(SQRT)) return true;
    if (jj_scan_token(52)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_76() {
    if (jj_3R_81()) return true;
    return false;
  }

  final private boolean jj_3R_29() {
    if (jj_3R_42()) return true;
    return false;
  }

  final private boolean jj_3R_75() {
    if (jj_3R_80()) return true;
    return false;
  }

  final private boolean jj_3R_28() {
    if (jj_3R_41()) return true;
    return false;
  }

  final private boolean jj_3R_74() {
    if (jj_3R_79()) return true;
    return false;
  }

  final private boolean jj_3R_27() {
    if (jj_3R_40()) return true;
    return false;
  }

  final private boolean jj_3R_73() {
    if (jj_3R_78()) return true;
    return false;
  }

  final private boolean jj_3R_26() {
    if (jj_3R_39()) return true;
    return false;
  }

  final private boolean jj_3R_46() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) {
    jj_scanpos = xsp;
    if (jj_3R_74()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) {
    jj_scanpos = xsp;
    if (jj_3R_76()) return true;
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_72() {
    if (jj_3R_77()) return true;
    return false;
  }

  final private boolean jj_3R_25() {
    if (jj_3R_38()) return true;
    return false;
  }

  final private boolean jj_3R_24() {
    if (jj_3R_37()) return true;
    return false;
  }

  final private boolean jj_3R_64() {
    if (jj_scan_token(EXPO)) return true;
    if (jj_scan_token(52)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_33() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) return true;
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_23() {
    if (jj_3R_36()) return true;
    return false;
  }

  final private boolean jj_3R_17() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_22() {
    if (jj_3R_35()) return true;
    return false;
  }

  final private boolean jj_3R_13() {
    if (jj_3R_17()) return true;
    if (jj_scan_token(49)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  final private boolean jj_3_1() {
    if (jj_3R_13()) return true;
    return false;
  }

  final private boolean jj_3R_19() {
    if (jj_scan_token(NABLA)) return true;
    return false;
  }

  final private boolean jj_3R_109() {
    if (jj_3R_18()) return true;
    return false;
  }

  final private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) return true;
    }
    return false;
  }

  final private boolean jj_3R_63() {
    if (jj_scan_token(FAC)) return true;
    if (jj_scan_token(52)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_108() {
    if (jj_3R_13()) return true;
    return false;
  }

  final private boolean jj_3R_95() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_108()) {
    jj_scanpos = xsp;
    if (jj_3R_109()) return true;
    }
    return false;
  }

  final private boolean jj_3R_82() {
    if (jj_scan_token(54)) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  final private boolean jj_3R_14() {
    if (jj_3R_17()) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  final private boolean jj_3R_32() {
    if (jj_3R_19()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_46()) jj_scanpos = xsp;
    return false;
  }

  final private boolean jj_3R_86() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3_2() {
    if (jj_3R_14()) return true;
    return false;
  }

  final private boolean jj_3R_117() {
    if (jj_3R_118()) return true;
    return false;
  }

  final private boolean jj_3R_93() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) return true;
    }
    return false;
  }

  final private boolean jj_3R_78() {
    if (jj_scan_token(SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_118() {
    if (jj_scan_token(POSTFIX)) return true;
    return false;
  }

  final private boolean jj_3R_116() {
    if (jj_3R_17()) return true;
    return false;
  }

  final private boolean jj_3R_115() {
    if (jj_3R_14()) return true;
    return false;
  }

  final private boolean jj_3R_92() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_69() {
    if (jj_scan_token(59)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(59)) return true;
    return false;
  }

  final private boolean jj_3R_68() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_95()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_105() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_91() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_106() {
    if (jj_scan_token(54)) return true;
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  final private boolean jj_3R_53() {
    if (jj_scan_token(51)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  final private boolean jj_3R_42() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_3R_69()) return true;
    }
    return false;
  }

  final private boolean jj_3R_113() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_115()) {
    jj_scanpos = xsp;
    if (jj_3R_116()) return true;
    }
    xsp = jj_scanpos;
    if (jj_3R_117()) jj_scanpos = xsp;
    return false;
  }

  final private boolean jj_3R_34() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) return true;
    }
    return false;
  }

  final private boolean jj_3R_52() {
    if (jj_scan_token(57)) return true;
    if (jj_3R_30()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_82()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(58)) return true;
    return false;
  }

  final private boolean jj_3R_41() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(40)) {
    jj_scanpos = xsp;
    if (jj_scan_token(41)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) {
    jj_scanpos = xsp;
    if (jj_scan_token(37)) {
    jj_scanpos = xsp;
    if (jj_scan_token(38)) return true;
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_114() {
    if (jj_scan_token(50)) return true;
    if (jj_3R_113()) return true;
    return false;
  }

  final private boolean jj_3R_90() {
    if (jj_scan_token(DERIVE)) return true;
    if (jj_scan_token(52)) return true;
    if (jj_3R_30()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_106()) jj_scanpos = xsp;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_110() {
    if (jj_3R_113()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_114()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_104() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_111() {
    if (jj_scan_token(DIVIDE)) return true;
    if (jj_3R_110()) return true;
    return false;
  }

  final private boolean jj_3R_77() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  final private boolean jj_3R_21() {
    Token xsp;
    if (jj_3R_34()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_34()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_103() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  final private boolean jj_3R_97() {
    if (jj_3R_110()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_111()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_62() {
    if (jj_scan_token(FORALL)) return true;
    if (jj_3R_93()) return true;
    return false;
  }

  final private boolean jj_3R_15() {
    if (jj_3R_20()) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  final private boolean jj_3R_61() {
    if (jj_scan_token(EXIST)) return true;
    if (jj_3R_92()) return true;
    return false;
  }

  final private boolean jj_3R_98() {
    if (jj_scan_token(MULTIPLICATIONSYMBOL)) return true;
    if (jj_3R_97()) return true;
    return false;
  }

  public fsParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  public Token token, jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  public boolean lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[38];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_0();
      jj_la1_1();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0xfffc0400,0x80,0xfffc0400,0x400,0x1000,0x8000,0x0,0xfffc0000,0x10000,0xfffc0000,0x0,0x0,0x0,0x0,0x18000000,0x700000,0x7f00000,0x0,0x60000000,0xc0000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x7810cf78,0x0,0x7810cf78,0x0,0x0,0x0,0x40000,0x7810cf78,0x0,0x7810cf78,0x100000,0x100000,0x2080000,0x7000c818,0x0,0x0,0x0,0x400000,0x0,0x0,0x400000,0x800000,0x400000,0x400000,0x400000,0x2080000,0x2080000,0x8100000,0x70008818,0x70008818,0x70008818,0x7000c818,0x70000000,0x8040,0x8040,0x8040,0x8040,0x760,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[4];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  public fsParser(java.io.InputStream stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new fsParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.InputStream stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public fsParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new fsParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public fsParser(fsParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(fsParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector jj_expentries = new java.util.Vector();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration e = jj_expentries.elements(); e.hasMoreElements();) {
        int[] oldentry = (int[])(e.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[64];
    for (int i = 0; i < 64; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 38; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 64; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

  final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 4; i++) {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
          }
        }
        p = p.next;
      } while (p != null);
    }
    jj_rescan = false;
  }

  final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
