/* Generated By:JJTree: Do not edit this line. math4u2\parser\formulaold\fsParserTreeConstants.java */

package math4u2.parser.formulaold;

public interface fsParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTNORMALEXPRESSION = 2;
  public int JJTPRAEFIXEXPRESSION = 3;
  public int JJTPRAEFIX = 4;
  public int JJTDIV = 5;
  public int JJTEXPO = 6;
  public int JJTPOSTFIXEXPRESSION = 7;
  public int JJTPOSTFIX = 8;
  public int JJTNABLAEXPRESSION = 9;
  public int JJTNABLA = 10;
  public int JJTNORMALFUNCTION = 11;
  public int JJTINDEXEDEXPRESSION = 12;
  public int JJTMATHFUNCTION = 13;
  public int JJTSPECIALFUNCTION = 14;
  public int JJTPDERIVE = 15;
  public int JJTDERIVE = 16;
  public int JJTBRACKETS = 17;
  public int JJTROOT = 18;
  public int JJTNUMBER = 19;
  public int JJTVECMATHDEFINITION = 20;
  public int JJTLISTEDEXPRESSIONS = 21;
  public int JJTBRACES = 22;
  public int JJTINDECES = 23;
  public int JJTVECMATHSYMBOL = 24;
  public int JJTUNDEFINEDVECTOR = 25;
  public int JJTUNDEFINEDMATRIX = 26;
  public int JJTIDENT = 27;
  public int JJTSYMBOL = 28;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "NormalExpression",
    "PraefixExpression",
    "Praefix",
    "Div",
    "Expo",
    "PostfixExpression",
    "Postfix",
    "NablaExpression",
    "Nabla",
    "NormalFunction",
    "IndexedExpression",
    "MathFunction",
    "SpecialFunction",
    "PDerive",
    "Derive",
    "Brackets",
    "Root",
    "Number",
    "VecmathDefinition",
    "ListedExpressions",
    "Braces",
    "Indeces",
    "VecmathSymbol",
    "UndefinedVector",
    "UndefinedMatrix",
    "Ident",
    "Symbol",
  };
}
