/* Generated By:JavaCC: Do not edit this line. KurzSchriftConstants.java */
package math4u2.parser.script;

public interface KurzSchriftConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int LPAREN = 9;
  int RPAREN = 10;
  int SEMICOLON = 11;
  int COMMA = 12;
  int DOT = 13;
  int ISTGLEICH = 14;
  int DEF = 15;
  int SPACE = 16;
  int ESCAPED_SC = 17;
  int ESCAPED_QM = 18;
  int ID = 19;
  int DESCRIPTION = 20;
  int MATHS = 21;
  int STRING_LITERAL = 22;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 8>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\":=\"",
    "<SPACE>",
    "\"\\\\;\"",
    "\"\\\\\\\"\"",
    "<ID>",
    "<DESCRIPTION>",
    "<MATHS>",
    "<STRING_LITERAL>",
  };

}
