/* Generated By:JJTree: Do not edit this line. C:\daten\math4u\math4u2\math4u2\parser\formula\fsParserTreeConstants.java */

package math4u2.parser.formula;

public interface fsParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTNORMALEXPRESSION = 2;
  public int JJTPRAEFIXEXPRESSION = 3;
  public int JJTPRAEFIX = 4;
  public int JJTDIV = 5;
  public int JJTEXPO = 6;
  public int JJTPOSTFIXEXPRESSION = 7;
  public int JJTPOSTFIX = 8;
  public int JJTSYMBOLEXPRESSION = 9;
  public int JJTSPECIALSYMBOL = 10;
  public int JJTMETHODPATH = 11;
  public int JJTFUNCTIONDETAILCHOOSER = 12;
  public int JJTMATHFUNCTION = 13;
  public int JJTSPECIALFUNCTION = 14;
  public int JJTDERIVE = 15;
  public int JJTNUMBER = 16;
  public int JJTPDERIVE = 17;
  public int JJTSYMBOL = 18;
  public int JJTBRACKETS = 19;
  public int JJTROOT = 20;
  public int JJTLIMES = 21;
  public int JJTVECMATHDEFINITION = 22;
  public int JJTEVALSTEP = 23;
  public int JJTBRACES = 24;
  public int JJTINDECES = 25;
  public int JJTIDENT = 26;
  public int JJTVECMATHSYMBOL = 27;
  public int JJTUNDEFINEDVECTOR = 28;
  public int JJTUNDEFINEDMATRIX = 29;
  public int JJTSPECIALIDENT = 30;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "NormalExpression",
    "PraefixExpression",
    "Praefix",
    "Div",
    "Expo",
    "PostfixExpression",
    "Postfix",
    "SymbolExpression",
    "SpecialSymbol",
    "MethodPath",
    "FunctionDetailChooser",
    "MathFunction",
    "SpecialFunction",
    "Derive",
    "Number",
    "PDerive",
    "Symbol",
    "Brackets",
    "Root",
    "Limes",
    "VecmathDefinition",
    "EvalStep",
    "Braces",
    "Indeces",
    "Ident",
    "VecmathSymbol",
    "UndefinedVector",
    "UndefinedMatrix",
    "SpecialIdent",
  };
}
