/* Generated By:JJTree&JavaCC: Do not edit this line. fsParserConstants.java */
package math4u2.parser.formula;

public interface fsParserConstants {

  int EOF = 0;
  int RELATIONSYMBOL = 7;
  int LT = 8;
  int GT = 9;
  int ARROW = 10;
  int REL_STRING_INFIX = 11;
  int ADDITIONSYMBOL = 12;
  int ADD_STRING = 13;
  int MULTIPLICATIONSYMBOL = 14;
  int MULT = 15;
  int MULT_STRING = 16;
  int DIVIDE = 17;
  int POSTFIX = 18;
  int STRING_PREFIX = 19;
  int FUNCTION_PREFIX = 20;
  int NABLA = 21;
  int VOIDELEMENT = 22;
  int DOTS = 23;
  int ROOT = 24;
  int SQRT = 25;
  int LIM = 26;
  int SUM = 27;
  int INT = 28;
  int PROD = 29;
  int DERIVE = 30;
  int PDERIVE = 31;
  int EXIST = 32;
  int FORALL = 33;
  int VARS = 34;
  int MATHFUNCTION = 35;
  int LOG = 36;
  int FAC = 37;
  int EXPO = 38;
  int POW = 39;
  int INVERSE = 40;
  int TRANSPOSE = 41;
  int VECMATH = 42;
  int MATRIX = 43;
  int VECTOR = 44;
  int DUALVEKTOR = 45;
  int VECMATHSYMBOL = 46;
  int UNDEFVECTOR = 47;
  int UNDEFMATRIX = 48;
  int FLOAT_LITERAL = 49;
  int INTEGER_LITERAL = 50;
  int DIGIT = 51;
  int ENUMBER = 52;
  int INFIN = 53;
  int EULER = 54;
  int PI = 55;
  int STRUCTURE = 56;
  int SYMBOL = 57;
  int GR_LETTER_LC = 58;
  int GR_LETTER_UC = 59;
  int IDENTIFIER = 60;
  int LETTER = 61;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<RELATIONSYMBOL>",
    "<LT>",
    "<GT>",
    "<ARROW>",
    "<REL_STRING_INFIX>",
    "<ADDITIONSYMBOL>",
    "<ADD_STRING>",
    "<MULTIPLICATIONSYMBOL>",
    "<MULT>",
    "<MULT_STRING>",
    "\"/\"",
    "<POSTFIX>",
    "<STRING_PREFIX>",
    "<FUNCTION_PREFIX>",
    "\"$nabla\"",
    "\"$void\"",
    "<DOTS>",
    "\"root\"",
    "\"sqrt\"",
    "<LIM>",
    "\"sum\"",
    "\"int\"",
    "\"prod\"",
    "\"derive\"",
    "\"pderive\"",
    "\"exist\"",
    "\"forall\"",
    "\"vars\"",
    "<MATHFUNCTION>",
    "\"log\"",
    "\"fac\"",
    "\"exp\"",
    "\"pow\"",
    "\"inverse\"",
    "\"transpose\"",
    "<VECMATH>",
    "\"matrix\"",
    "\"vektor\"",
    "\"dualvektor\"",
    "<VECMATHSYMBOL>",
    "<UNDEFVECTOR>",
    "<UNDEFMATRIX>",
    "<FLOAT_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DIGIT>",
    "<ENUMBER>",
    "\"$infin\"",
    "\"e\"",
    "\"$pi\"",
    "<STRUCTURE>",
    "<SYMBOL>",
    "<GR_LETTER_LC>",
    "<GR_LETTER_UC>",
    "<IDENTIFIER>",
    "<LETTER>",
    "\":=\"",
    "\",\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"_\"",
    "\"|\"",
    "\".\"",
    "\"~\"",
  };

}
