/* Generated By:JavaCC: Do not edit this line. parserConstants.java */
package math4u2.parser;

public interface parserConstants {

  int EOF = 0;
  int EOL = 4;
  int PLUS = 5;
  int MINUS = 6;
  int MULTIPLY = 7;
  int SCALARPRODUCT = 8;
  int DIVIDE = 9;
  int EXP = 10;
  int FAC = 11;
  int ASSIGN = 12;
  int LT = 13;
  int GT = 14;
  int SUM = 15;
  int PRODUCT = 16;
  int DERIVE = 17;
  int PDERIVE = 18;
  int VARS = 19;
  int CURVE = 20;
  int COMPOUNDCURVE = 21;
  int POINT = 22;
  int MARKER = 23;
  int BAR = 24;
  int DISCRETE = 25;
  int DISCRETESEQ = 26;
  int FIELD = 27;
  int TEXTELEMENT = 28;
  int AREA = 29;
  int PFEIL = 30;
  int STRETCH = 31;
  int BEZIER = 32;
  int CIRCLE = 33;
  int ANGLE = 34;
  int STRAIGHT = 35;
  int FUNCTION = 36;
  int LIST = 37;
  int LIST0 = 38;
  int SEQUENCE = 39;
  int SEQUENCE0 = 40;
  int SCALAR = 41;
  int MATRIX = 42;
  int DIAGMATRIX = 43;
  int EMATRIX = 44;
  int VECTOR = 45;
  int DUALVECTOR = 46;
  int KARTE = 47;
  int DIGIT = 48;
  int SMALLLETTER = 49;
  int CAPITALLETTER = 50;
  int LETTER = 51;
  int BRACKET = 52;
  int PUNCTATION = 53;
  int MATHSYMBOL = 54;
  int STRING_LITERAL = 55;
  int Zahl = 56;
  int FLOAT = 57;
  int INTEGER = 58;
  int Bezeichner = 59;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"$\"",
    "\"/\"",
    "\"^\"",
    "\"!\"",
    "\":=\"",
    "\"<\"",
    "\">\"",
    "\"sum\"",
    "\"prod\"",
    "\"derive\"",
    "\"pderive\"",
    "\"vars\"",
    "<CURVE>",
    "<COMPOUNDCURVE>",
    "<POINT>",
    "\"marker\"",
    "\"balken\"",
    "\"punkte\"",
    "\"punktFolge\"",
    "\"feld\"",
    "\"text\"",
    "<AREA>",
    "<PFEIL>",
    "<STRETCH>",
    "\"bezier\"",
    "<CIRCLE>",
    "<ANGLE>",
    "<STRAIGHT>",
    "<FUNCTION>",
    "<LIST>",
    "<LIST0>",
    "\"folge\"",
    "\"folge0\"",
    "<SCALAR>",
    "\"matrix\"",
    "\"diagmatrix\"",
    "\"ematrix\"",
    "<VECTOR>",
    "<DUALVECTOR>",
    "\"karte\"",
    "<DIGIT>",
    "<SMALLLETTER>",
    "<CAPITALLETTER>",
    "<LETTER>",
    "<BRACKET>",
    "<PUNCTATION>",
    "<MATHSYMBOL>",
    "<STRING_LITERAL>",
    "<Zahl>",
    "<FLOAT>",
    "<INTEGER>",
    "<Bezeichner>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
  };

}
